// Source images are baked from Sanity at full resolution (~1500px wide .webp) and
// rendered into far smaller slots. The Sanity CDN applies transforms on the fly via
// query params, so we cap the delivered width and opt into `auto=format` (serves AVIF
// to supporting browsers) — together an ~80–90% transfer cut with no build step.
//
// Done in code rather than in content/settings.json on purpose: those URLs are
// regenerated by the Sanity bake (scripts/sanity-bake.mjs) and would lose any edits.
// Non-Sanity URLs (local /app/... paths, data URIs) pass through untouched.
export function sized(url: string, width: number, quality = 70): string {
  if (!url || !url.includes("cdn.sanity.io")) return url;
  const sep = url.includes("?") ? "&" : "?";
  // fit=max keeps the full image (no crop, no upscale); CSS object-fit handles framing.
  return `${url}${sep}auto=format&fit=max&w=${Math.round(width)}&q=${quality}`;
}
