import { defineField, defineType } from "sanity";

const imageKeys: { name: string; title: string }[] = [
  { name: "hero", title: "Hero" },
  { name: "interior", title: "Interior" },
  { name: "bar", title: "Bar" },
  { name: "event", title: "Event" },
  { name: "food", title: "Food" },
  { name: "terrace", title: "Terrasse" },
  { name: "facade", title: "Fassade" },
  { name: "foodTwo", title: "Food 2" },
  { name: "drink", title: "Drink" },
  // Per-position feature slots (home page) — independently swappable.
  { name: "heroStripLeft", title: "Hero-Streifen links" },
  { name: "heroStripRight", title: "Hero-Streifen rechts" },
  { name: "introOne", title: "Intro-Slide 1" },
  { name: "introTwo", title: "Intro-Slide 2" },
  { name: "introThree", title: "Intro-Slide 3" },
  { name: "menuMedia", title: "Menü-Sektion Bild" },
  { name: "stripOne", title: "Impressionen 1" },
  { name: "stripTwo", title: "Impressionen 2" },
  { name: "stripThree", title: "Impressionen 3" },
  { name: "stripFour", title: "Impressionen 4" },
  { name: "stripFive", title: "Impressionen 5" },
  { name: "setsImage", title: "Musik-Sektion Bild" },
  { name: "host", title: "Gastgeber" },
  // Event-Karten (Startseite) + Unterseiten-Bilder.
  { name: "cardPrivate", title: "Karte Private Events" },
  { name: "cardCorporate", title: "Karte Corporate Events" },
  { name: "privateHero", title: "Private Events — Hero" },
  { name: "privateDetail", title: "Private Events — Detail" },
  { name: "privateAtmosphere", title: "Private Events — Atmosphäre" },
  { name: "corporateHero", title: "Corporate Events — Hero" },
  { name: "corporateDetail", title: "Corporate Events — Detail" },
  { name: "corporateAtmosphere", title: "Corporate Events — Atmosphäre" },
  // Thumb cards (Drinks-Sektion unterhalb des Videos).
  { name: "thumbSignature", title: "Thumb Signature Drinks" },
  { name: "thumbKlassiker", title: "Thumb Klassiker" },
  { name: "thumbChampagner", title: "Thumb Champagner" },
  // Polaroid wall (Über-uns-Sektion) — 10 per-position slots.
  { name: "polaroidOne", title: "Polaroid 1" },
  { name: "polaroidTwo", title: "Polaroid 2" },
  { name: "polaroidThree", title: "Polaroid 3" },
  { name: "polaroidFour", title: "Polaroid 4" },
  { name: "polaroidFive", title: "Polaroid 5" },
  { name: "polaroidSix", title: "Polaroid 6" },
  { name: "polaroidSeven", title: "Polaroid 7" },
  { name: "polaroidEight", title: "Polaroid 8" },
  { name: "polaroidNine", title: "Polaroid 9" },
  { name: "polaroidTen", title: "Polaroid 10" },
];

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Einstellungen",
  type: "document",
  groups: [
    { name: "business", title: "Betrieb", default: true },
    { name: "media", title: "Medien" },
    { name: "labels", title: "Labels" },
  ],
  fields: [
    defineField({ name: "siteName", title: "Name", type: "string", group: "business", validation: (r) => r.required() }),
    defineField({ name: "shortName", title: "Kurzname", type: "string", group: "business" }),
    defineField({ name: "title", title: "SEO-Titel", type: "string", group: "business", validation: (r) => r.required() }),
    defineField({ name: "description", title: "SEO-Beschreibung", type: "text", rows: 3, group: "business" }),
    defineField({ name: "phone", title: "Telefon", type: "string", group: "business" }),
    defineField({ name: "email", title: "E-Mail", type: "string", group: "business" }),
    defineField({ name: "instagram", title: "Instagram-URL", type: "url", group: "business" }),
    defineField({
      name: "address",
      title: "Adresse",
      type: "object",
      group: "business",
      fields: [
        defineField({ name: "street", title: "Straße", type: "string" }),
        defineField({ name: "postalCode", title: "PLZ", type: "string" }),
        defineField({ name: "city", title: "Stadt", type: "string" }),
        defineField({ name: "country", title: "Land (Code)", type: "string" }),
      ],
    }),
    defineField({
      name: "hours",
      title: "Öffnungszeiten",
      type: "array",
      group: "business",
      of: [
        {
          type: "object",
          fields: [
            { name: "day", title: "Tag", type: "string" },
            { name: "hours", title: "Zeiten", type: "string" },
          ],
          preview: { select: { title: "day", subtitle: "hours" } },
        },
      ],
    }),
    defineField({ name: "menuPdf", title: "Getränkekarte (PDF)", type: "file", group: "media" }),
    defineField({ name: "menuPageCount", title: "Seitenanzahl", type: "number", group: "media" }),
    defineField({ name: "menuVideo", title: "Menü-Sektion Video", type: "file", group: "media" }),
    defineField({ name: "setsVideo", title: "Musik-Sektion Video", type: "file", group: "media" }),
    defineField({
      name: "images",
      title: "Bilder",
      type: "object",
      group: "media",
      fields: imageKeys.map((k) => defineField({ name: k.name, title: k.title, type: "imageWithAlt" })),
    }),
    defineField({
      name: "labels",
      title: "Struktur-Labels",
      type: "object",
      group: "labels",
      fields: [
        defineField({ name: "tagline", title: "Tagline (Topbar & Loader)", type: "string" }),
        defineField({ name: "heroStrip", title: "Hero-Streifen (3 Wörter)", type: "array", of: [{ type: "string" }] }),
        defineField({ name: "metaRow", title: "Meta-Zeile", type: "array", of: [{ type: "string" }] }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "Einstellungen" }) },
});
